name: Node CI

on: [pull_request, push]

jobs:
  build:
    name: Production Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      - name: Install dependencies
        uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # v1.12.1
      - name: Production Test Action
        uses: ./
        with:
          script: test:ci
          verbose: true
